### ISSUE TITLE
Implement Pure KL Kraken Rig

### ISSUE THREAD

**Issue by phtaylor** [fabric-engine/Kraken#101]
It should be quite possible to build a pure KL Kraken rig. Doing this would be a good exercise and highlight other usecases for Kraken than just Hero rigs. The important issue would be that the KL rig would compute the exact same pose as the rig in Maya/Softimage/3dsmax.

Note: After thinking about this for the last few days, I do think its not a majior project. 

Would be usefull for the following usse cases.
 - Standalone rig debuggers/preview tools
 - Crowd systems
 - Game runtimes
 -

**Comment by EricTRocks** [comment]
While it hasn't been done in KL, @helgemathee has implemented this via Canvas nodes and builder in #343
