### ISSUE TITLE
Add functionality to have Kraken graph say if connections can be made

### ISSUE THREAD

**Issue by EricTRocks** [fabric-engine/Kraken#220]
Currently we're checking if ports can be connected inside the UI code instead of calling methods on the Kraken graph. The UI shouldn't be doing the checking.

**Comment by EricTRocks** [comment]
@phtaylor We need to identify where this is happeing in the UI code and where it needs to go in the core.

**Comment by phtaylor** [comment]
in knode, there is a method called def canConnectTo(self, otherPortCircle):, which can call back into the Rig.py file to ask if a connection can be made.
