### ISSUE TITLE
Improve how constraints are set

### ISSUE THREAD

**Issue by ahmidou** [fabric-engine/Kraken#241]
Currently a constraint need to get it's IO as arguments plus to be added to the output object, so we need to set twice the output.
wouldn't it be more elegant to have a have just one or the other way to set the output?

**Comment by EricTRocks** [comment]
Can you post an example? You create the constraint, with a name argument.
Then assign the constrainer and add the constraint to the target. You
shouldn't need to specify anything twice.

**Comment by ahmidou** [comment]
My mistake, I just figured that the argument is the name...
