### ISSUE TITLE
Kraken UI Slow, and slowing the host UI

### ISSUE THREAD

**Issue by ahmidou** [fabric-engine/Kraken#242]
I have a kraken graph with 57 nodes, and moving the graph window on the screen is very slow.
It's also slowing down the DCC windows (both maya and SI)

**Comment by yamahigashi** [comment]
I fond that [connection.prepareGeometryChange()](https://github.com/fabric-engine/Kraken/blob/master/Python/kraken/ui/GraphView/graph_view/connection.py#L96)] causes this issue.
```python
    def paint(self, painter, option, widget):
        ...

        self.__path = QtGui.QPainterPath()
        self.__path.moveTo(srcPoint)
        self.__path.cubicTo(
            srcPoint + QtCore.QPointF(dist_between.x() * 0.4, 0),
            dstPoint - QtCore.QPointF(dist_between.x() * 0.4, 0),
            dstPoint
            )
        self.setPath(self.__path)
        self.prepareGeometryChange()  # <=   this
        super(Connection, self).paint(painter, option, widget)
```

but, deleting this invocation causes trivial disturbance in graphview when dragging a node.

**Comment by phtaylor** [comment]
thanks Yamahigashi! We'll take a look and see how we can optimize this.

**Comment by EricTRocks** [comment]
From what I've read and looked at this might be a bit of a cyclic issue. The docs say that prepareGeometryChange() calls .update() which will redraw (call the paint() method) and I think this is causing a cycle of a bunch of updates. Instead I think we need to be putting prepareGeometryChange() into the methods that cause the change not the one that redraws it such as the move methods.

https://pyside.github.io/docs/pyside/PySide/QtGui/QGraphicsItem.html#PySide.QtGui.PySide.QtGui.QGraphicsItem.prepareGeometryChange

**Comment by phtaylor** [comment]
I think that makes a lot of sense. We probably also need test graphs with hundreds of conencted nodes so we can test this regularly.
