### ISSUE TITLE
[Softimage] Kraken UI prevent calling new scene command whith keyboard shortcuts

### ISSUE THREAD

**Issue by ahmidou** [fabric-engine/Kraken#243]
Just open a UI and press ctrl-n. it's kind of queuing the call and If you close the kraken UI, then the command is executed

**Comment by EricTRocks** [comment]
This is most likely a PyQtForSoftimage bug not a Kraken bug.

**Comment by ahmidou** [comment]
An empty Kraken window is quite fast, so I was wondrering.

**Comment by ahmidou** [comment]
OK
