### ISSUE TITLE
[GUI] Nodes and in/out of nodes

### ISSUE THREAD

**Issue by ilayshp** [fabric-engine/Kraken#272]
Hello

I test Kraken(dev-2x) gui in dcc(c4d r17) and got such glitch. Visualize node as transparent, ports same. Sys.settings are Win8 x64, c4d r17, Python 2.7, Pyside 1.2.2, FE 2.0.0

![c4d](https://cloud.githubusercontent.com/assets/2669688/10606734/b1225112-7756-11e5-9688-195425515827.png)

**Comment by phtaylor** [comment]
ok, this is quite strange. 

Are you able to try running the UI from the console?
e.g. launch a bash shell, and launch the kraken_window.py python script directly. You should be able to load and see your rigs there. 


first source the environment.sh file, and then run Python/kraken/ui/kraken_window.py
you may need to first source the environment.sh file in your FabricEngine folder

**Comment by EricTRocks** [comment]
I'd also check and see what versions of PyQt / PySide C4D is using. Maybe there is an incompatibility there?

**Comment by ilayshp** [comment]
@EricTRocks 
C4D does not use PyQt / PySide natively like maya. from r17 version, maxon choose py2.7... before was 2.6
> Maybe there is an incompatibility there?

Probably.

@phtaylor
> Are you able to try running the UI from the console?

i'm making similar script as maya-dcc plug-in to show Kraken and work with it in c4d environment. Most of all environment vars are in computer settings or declared by _os.environ_ or similar...(btw, from Kraken settings - Fabric Path,  from Fabric team - Fabric_Dir). Such
```python
import os, sys
import json

sys.path.append('o:/FabricEngine/Python/2.7')
sys.path.append('o:/FabricEngine/Kraken/Python')
sys.path.append('o:/FabricEngine/Kraken/KLExts')

os.environ['FABRIC_DIR']='o:/FabricEngine'

os.environ['FABRIC_PATH']='o:/FabricEngine'
os.environ['KRAKEN_PATH']='o:/FabricEngine/Kraken'

from PySide import QtCore, QtGui, QtOpenGL
from PySide.QtCore import *
from PySide.QtGui import *
from PySide.QtOpenGL import *

import FabricEngine.Core as fabric
from FabricEngine.Core import *

try:
    import PySide.shiboken as shiboken
except:
    import shiboken

import types

import kraken
import kraken.ui.kraken_window
from kraken.ui.kraken_window import KrakenWindow
from kraken.ui.kraken_window import createSplash 

from kraken.core.objects.rig import Rig
from kraken import plugins

import c4d

def main():
    
    app = QtGui.QApplication.instance()
    
    if not app:
          app = QtGui.QApplication([]) 

    for widget in app.topLevelWidgets():
        if widget.objectName() == 'KrakenMainWindow':
            widget.showNormal()
    
    splash = createSplash(app)
    win = KrakenWindow()
    
    win.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
    win.setProperty("saveWindowPref", True )
    
    splash.finish(win)
    if win.isVisible() == False:
        win.show()
        app.exec_()

if __name__ == "__main__":
  main()
```

**Comment by ilayshp** [comment]
me again, i'm sorry, i resolve by compilng of pyside v.1.2.4, install it and kraken works with it

![resolved](https://cloud.githubusercontent.com/assets/2669688/10640605/3b36746a-7837-11e5-8081-f205a546198a.png)

**Comment by EricTRocks** [comment]
Great to see you figure this out. The only thing is that you'll need to have a Fabric plugin for C4D for this to work 100% plus a C4D Kraken plug-in too. Are you working on this?

**Comment by ilayshp** [comment]
I will to try, if it will possible to connect c4d's char system and maybe cactus dan's char tools(plug-in for c4d)
