### ISSUE TITLE
Joint should be created as an implicit bone instead of a null in softimage

### ISSUE THREAD

**Issue by fchancrin** [fabric-engine/Kraken#280]
When we build a Joint in softimage, the object created is a null.It would be better if it was a bone implicit, this way it'll be translated as a bone in case of an FBX export.
No need to take care of the bone shape in softimage, we can just use a cube or a null shape.

**Comment by EricTRocks** [comment]
Do the Joint implicits still have problems with the symmetry skinning tools? If so we don't want to use those by default and will probably need to create another layer for mocap specific objects that use the Joint
