### ISSUE TITLE
Need to be able to connect object visibility to other attributes

### ISSUE THREAD

**Issue by EricTRocks** [fabric-engine/Kraken#289]
Users need to be able to drive the visibility of control objects via parameters that also drive the FKIK blend on components such as arms and legs. Currently Kraken does not have a way to hook into the visibility attribute on objects in the DCC's. We simply have a setVisibility() method in the builders that looks at a _visibility attribute on the object3d objects. We'll need to expose that as a proper BooleanAttribute object to do this work.

I think the work that would need to be done would be as follows:
- Switch the '_visibility' attribute to a BooleanAttribute object on the object3D object.
- Users would need a method of finding this Kraken attr. through a method such as 'getVisibilityAttr'
- Users could then use the standard .connect() method for attributes to connect the attr driven by the solver, to the visibility attr.
- We'd have to re-evaluate how we set object visibility in conjunction to this (or not) as we have the .setVisibility and .setShapeVisibility methods already.
- Add a method / block of code in the builder's 'setVisibility()' method to create direct connections (Maya) / expressions (Softimage) to other attributes if they are connected.

**Comment by BigRoy** [comment]
Is this already possible?

**Comment by EricTRocks** [comment]
No it's something that has come up a few times and we need to refactor
where object visibility is set and handled.

**Comment by EricTRocks** [comment]
Fixed in 7daa2e4
