### ISSUE TITLE
Make Kraken graph navigation match Maya (DCC) node graph navigation

### ISSUE THREAD

**Issue by todderasesareddot** [fabric-engine/Kraken#292]
It's subtle, but I run into this constantly when switching between Maya node graph and Kraken UI.  Need the ability to make the mouse/keyboard controls the same for both either through a Kraken preference or for Kraken to automatically match the host DCC style.

(need to be able to disable scroll wheel for middle mouse pan, too)

**Comment by EricTRocks** [comment]
We're trying to mirror Canvas close to 1:1 with some enhancements. This is a valid request though and we'll have to investigate what implications it may have.

**Comment by todderasesareddot** [comment]
The options to use MMB to pan works great, but we also need Atlt+RMB for Zoom option to match maya's graph editor navigation.
