### ISSUE TITLE
Rename KLExts and CanvasPresets

### ISSUE THREAD

**Issue by EricTRocks** [fabric-engine/Kraken#294]
Suggested by @bhaux 

With studios wanting to contribute to the project, we should be consistent in how Fabric sets up their Exts and DFG directories.

We should rename our KLExts to Exts and CanvasPrests to DFG.

We should also organize / setup a folder structure that mimics how we have the Extensions organized:
DFG/Solvers
DFG/Utils
DFG/Drawing

Also any DFG presets that have been generated from KL Extensions should go into a sub-folder of the KL Extensions called DFG:

Exts/Solvers/DFG/TwoBoneIKSolver.preset

Users will then be able to mimic this directory in their own folder structure and copy in to the Kraken one when sharing presets and KL Extensions.

**Comment by bhaux** [comment]
Oh I just filed a similar issue. Sorry - feel free to merge ...

One change to your comment would be to truly consistent and mirror fabric's structure 
and make 

CanvasPresets/Kraken
 -> Presets/DFG/Kraken
 -> Presets/DFG/Oculus/...

KLExts/Kraken
 -> Exts/Kraken/
 -> Exts/Oculus/...

Other Examples:

Extensions:
Exts/**Kraken**/Solvers/DFG/TwoBoneIKSolver.preset
Exts/**Oculus**/Drawing/DFG/DebugAxis.preset

Preset:
Presets/DFG/Oculus/Components/SpineComponent.canvas

etc...
