### ISSUE TITLE
Restructuring: Extensions and Presets

### ISSUE THREAD

**Issue by bhaux** [fabric-engine/Kraken#296]
I would like to throw out a few thoughts Eric and I quickly chatted about and decided to put an issue on github.

**Kraken concept of Presets and Extensions**
I understand that currently, in Kraken, the difference between an extension and a preset is technical: 
an extention is pure KL *(Kraken/KLExts)* and a preset is a DFG *(Kraken/CanvasPresets)*.

**Fabric concept of Presets and Extensions**
In Fabric, however the difference is conceptual: an extension *(Fabric/Ext)* is extending Fabric's core functionality, or wrapping other libraries. Presets *(Fabric/Presets)* are high level functions, building upon existing Core and Extended fabric functionality.
An important note is that Fabric doesn't make a distinction between Canvas vs KL. While Presets can by their nature only be defined as canvas files, most Fabric functionality that is Core or Extended also has a DFG representation in the (Fabric/Ext/ExtName.(..)DFG/...).

So when I tried to figure out where to put my BSPline Extension (with their DFG definitions) as well as when I stumbled upon ...
    Kraken\CanvasPresets\Kraken\DirectionConstraintSolver.canvas
    Kraken\KLExts\Solvers\KrakenDirectionConstraintSolver.kl
... I was a little bit puzzled.

**The proposal**
- extensions are non-specific building blocks and can contain DFG representations of themselves
- presets are specific wrappers for convenience/workflow (e.g. FootRoll).
- Unify Kraken/Fabric convention: Rename 'KLExts' to 'Exts'. and 'CanvasPresets' to 'Presets'
- create subdirectories for Extensions and presets:
e.g.

*Kraken/Exts/Kraken/Solvers
*Kraken/Exts/Kraken/Manipulation
*Kraken/Exts/Kraken/Drawing
*Kraken/Exts/Oculus/Solvers

*Kraken/Presets/Kraken/Solvers
*Kraken/Presets/Oculus/Drawing/DFG

That way when merging there would be less likely an overlap, and since the Kraken code would mirror exactly the Fabric extension structure, it would be easier for fabric to pull in one of our extensions if general enough.

All in all, this is up for discussion. While it is somewhat a mystery when an extension turns into a preset (Solver/FootRollSolver.kl/DFG/FootRollSolver.canvas?) - all that is really important to me is that we are on one page, match Fabric whenever we can, and I have a place to put my Curves Extension, that I can deploy seamlessly with our new Spine ;)

Bernhard

**Comment by BigRoy** [comment]
Referencing another issue that just popped up with similar requests: #294.

This one though is more explicit about why/how and seems to have a good direction. Stick to the feeling of how Fabric provides Extensions and Presets. +1

(Minor note: Haven't used Kraken yet, but I'm watching it closely and when some looser deadline allows I'll hop straight in to have a play. Anything that makes it feel more familiar will be great!)
