### ISSUE TITLE
No module named pyflowgraph.node

### ISSUE THREAD

**Issue by BigRoy** [fabric-engine/Kraken#298]
I pulled the current state of the `develop2.x` branch yet I'm getting some errors when running Kraken.

In Maya when loading the plug-in.

```python
// Error: line 1: No module named pyflowgraph.node
# Traceback (most recent call last):
#   File "P:/NETRENDER/app_shared/Kraken/DCCIntegrations/maya/plug-ins/kraken_maya.py", line 10, in <module>
#     import kraken.ui.kraken_window
#   File "P:\NETRENDER\app_shared\Kraken\Python\kraken\ui\kraken_window.py", line 7, in <module>
#     import kraken.ui.kraken_ui
#   File "P:\NETRENDER\app_shared\Kraken\Python\kraken\ui\kraken_ui.py", line 12, in <module>
#     from GraphView.kgraph_view_widget import KGraphViewWidget
#   File "P:\NETRENDER\app_shared\Kraken\Python\kraken\ui\GraphView\kgraph_view_widget.py", line 9, in <module>
#     from contextual_node_list import ContextualNodeList
#   File "P:\NETRENDER\app_shared\Kraken\Python\kraken\ui\GraphView\contextual_node_list.py", line 11, in <module>
#     from knode import KNode
#   File "P:\NETRENDER\app_shared\Kraken\Python\kraken\ui\GraphView\knode.py", line 10, in <module>
#     from pyflowgraph.node import Node
# ImportError: No module named pyflowgraph.node // 
// Warning: line 1: Failed to run file: P:/NETRENDER/app_shared/Kraken/DCCIntegrations/maya/plug-ins/kraken_maya.py // 
# Error: pymel : Failed to get controlCommand list from kraken_maya # 
# Error: pymel : Failed to get modelEditorCommand list from kraken_maya # 
# Error: pymel : Failed to get command list from kraken_maya # 
# Error: pymel : Failed to get constraintCommand list from kraken_maya # 
# Error: pymel.core : Failed to get depend nodes list from kraken_maya # 
// Error: line 1:  (kraken_maya) // 
```

When running one of the UIs with:

```
cd %KRAKEN_PATH%/Python/kraken/ui
call cmd /k "python kraken_window.py"
```

I get:

```
Traceback (most recent call last):
  File "kraken_window.py", line 7, in <module>
    import kraken.ui.kraken_ui
  File "P:\NETRENDER\app_shared\Kraken\Python\kraken\ui\kraken_ui.py", line 12, in <module>
    from GraphView.kgraph_view_widget import KGraphViewWidget
  File "P:\NETRENDER\app_shared\Kraken\Python\kraken\ui\GraphView\kgraph_view_widget.py", line 9, in <module>
    from contextual_node_list import ContextualNodeList
  File "P:\NETRENDER\app_shared\Kraken\Python\kraken\ui\GraphView\contextual_node_list.py", line 11, in <module>
    from knode import KNode
  File "P:\NETRENDER\app_shared\Kraken\Python\kraken\ui\GraphView\knode.py", line 10, in <module>
    from pyflowgraph.node import Node
ImportError: No module named pyflowgraph.node
```

Documentation doesn't say anything on prerequisites or on installation of `pyflowgraph`. 
Is this is a new dependency?

---

My environment through a `.bat` file:

```
:: Set Kraken Environment

:: Kraken
set KRAKEN_PATH=%~dp0
REM Remove trailing backslash if there is one
IF %KRAKEN_PATH:~-1%==\ SET KRAKEN_PATH=%KRAKEN_PATH:~0,-1%

set KRAKEN_PATHS=%KRAKEN_PATH%/extraComponents;

:: Kraken PythonPath
set PYTHONPATH=%KRAKEN_PATH%/Python;%PYTHONPATH%

:: Fabric Extension and DFG Paths for Kraken
set FABRIC_DFG_PATH=%KRAKEN_PATH%/CanvasPresets;%FABRIC_DFG_PATH%
set FABRIC_EXTS_PATH=%KRAKEN_PATH%/KLExts;%FABRIC_EXTS_PATH%

```

**Comment by BigRoy** [comment]
Nevermind I think I just saw it here on github as a subrepository so it's included within Kraken yet somehow it didn't come along with my pull of the repo.

**Comment by EricTRocks** [comment]
Hey @BigRoy 

Sorry for the issues. I just fixed the logger issue a day or so ago I thought. You have pulled the latest in? There is a couple commits stating "Fixing logger" or similar that should be there specifically to fix the logger issue. If not, you can copy the logger file from the develop1.X branch to get going.

For PyFlowGraph, it should clone correctly into the subdir. Unless there are some settings not looking for submodules. Maybe it's a git version issue?

**Comment by EricTRocks** [comment]
Ah actually I'll redo those and push a fix. They were on a branch I trashed. Apologies, I'll get that soon.

**Comment by BigRoy** [comment]
Apparently the `pyflowgraph` submodule doesn't come along when download the `.zip` from the Github page or when forking and cloning the repository.

Also doing `git submodule update --init --recursive` didn't work since it raises an error that it doesn't have the permissions to pull that specific repository. (Not entirely sure why?)

So I still think this is very confusing to newcomers. Especially because there's no current documentation about this.

Similarly I'm getting the following logged message:
`Invalid Kraken Path: P:\NETRENDER\app_shared\git\kraken\extraComponents`

This path is not within the repository yet the `environment.sh` adds it. I can't find any documentation what that specific path is for. Is there any reason to still add that to the path?

**Comment by EricTRocks** [comment]
Yes the .zip does not include it which is annoying and I just found out about. I emailed Github support to ask for them to support submodules in zip downloads.

For the permissions thing try this:
in git bash at the Kraken repo dir run:
- git submodule deinit Python/kraken/ui/GraphView/pyflowgraph/
- git submodule update --init --recursive

There is no documentation as the develop2.X branch is still wip. I'll update docs soon regarding all of the changes but things have been changing a lot and drafting docs when things are still WIP isn't a good idea for time.

Not sure why that last path is getting added at all.

**Comment by BigRoy** [comment]
Thanks. I'm still getting this on the update init:

```
Cloning into 'Python/kraken/ui/GraphView/pyflowgraph'...
Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:HordeSoftware-co/pyflowgraph.git' into submodule path 'Python/kraken/ui/GraphView/pyflowgraph' failed
```
