### ISSUE TITLE
Add Kraken UI option to only have one guide rig and real rig in the scene at one time.

### ISSUE THREAD

**Issue by todderasesareddot** [fabric-engine/Kraken#314]
Currently, Kraken will add multiple rigs and guide rigs to the current scene when building from the UI.  I normal workflows, it is annoying/confusion to have multiples of the same thing in the scene at the same time.  

Have an option (default hopefully) to keep a max of 1 guide rig and 1 real rig in the scene at one time.  This keeps things much simpler for the user.

If a guide rig exists, building from the UI will initiate a sync, then delete the existing guide rig, then rebuild a new guide rig.  This assures there is never any data loss from editing of the in-scene guide rig.

If a real rig exists, delete that rig and rebuild a new one.

**Comment by todderasesareddot** [comment]
Implemented in commit e6e020ff3fc61d4bad9b1bbb0092e10b2b0b5800

**Comment by EricTRocks** [comment]
This was merged from Oculus in #344
