### ISSUE TITLE
Loading presets (.canvas) through kraken throws error - json parser needs to understand line-breaks

### ISSUE THREAD

**Issue by bhaux** [fabric-engine/Kraken#315]
It seems that saving/loading out Presets (.canvas) files through fabric works, however those same presets don't work when loaded through kraken.

The kraken parser seems to not understand the line breaks in the kl code snippets and throws an error. Bringing the code snippets into a single line will load the file successfully.

//
"code" : "require Math;
dfgEntry {
  result = this.translation();
}
"

vs

"code" : "require Math;\n dfgEntry { \n result = this.translation(); \n }"

This issue has come up a lot recently ... wonder if there is a quick way to bring the parser into compliance with the one deployed with fabric?

**Comment by EricTRocks** [comment]
Todd mentioned that it was not removing returns:

`
Got it.  That preprocessing coded needed to strip out the carraige return, as well.  fileContents = "".join(fileContents.split('\r'))
`

**Comment by bhaux** [comment]
aha! thanksTodd!
