### ISSUE TITLE
Constraints and Operators should check if they eval

### ISSUE THREAD

**Issue by EricTRocks** [fabric-engine/Kraken#321]
Constraints and Operators need to have their .evaluate() methods called on them when data is loaded onto them. It would be beneficial to add a step in the build process that checks if this has been done. If it has not it should log an error or warning.

Ops and Constraints need an attribute ".hasEvaluated" which the builder will check upon building it and log the error if it hasn't.

**Comment by todderasesareddot** [comment]
Note, this is only important for constraints/operators that are going to affect the location of component outputs after the buildHierarchy() step.  On the flip side, any constraint that is driven by a component input should complain if maintainOffset is set to False.

**Comment by EricTRocks** [comment]
While usually, the objects constrained to an input would want maintainOffset ON, some may want it to be off as well. We'll leave that check out but just check for `.evalaute()`
