### ISSUE TITLE
Default color names in config should be standard and comprehensive.

### ISSUE THREAD

**Issue by todderasesareddot** [fabric-engine/Kraken#330]
Right now there are about 30 named colors in the config.py.  If we are going to use names for colors (which I think is a good idea because human readable) we should just make it comprehensive and standard by following something like the established HTML color codes. 

http://www.w3schools.com/colors/colors_hex.asp

That way we get 150 by default and are all talking the same language.

Also, we should be able to set an object color by name or by rgb value.  That is myObject.setColor should be polymorphic and take either a string or Color object.  In the same vein, we should be able to give rgb values in the colorMap of the config.py.

**Comment by todderasesareddot** [comment]
This would be easy to do and I'm willing to implement and test in our branch today.

**Comment by EricTRocks** [comment]
Yes we have to figure out at what version Maya implemented the ability to set colors of objects by RGB values and make that a minimum requirement if we do this. Maya hasn't always supported this, thus why having the named colors was done.

I also agree this would be helpful to have the color be set by string or RGB. @phtaylor implemented a proper ColorAttribute object a little while ago and wanted to integrate that with this somehow.

I'm up for you implementing this. If you do I'd create a branch specific for this implementation and do the work for it and a pull request for just these changes. :) What may also be needed is to update the example components to adapt these new color names and work.

**Comment by todderasesareddot** [comment]
Looks like Maya 2015.  Yeah, I totally remember having to set those cryptic number for curve colors.  Finally!
Yeah, I'll make a new branch for this feature.  I've been wanting to start doing that anyway.

**Comment by EricTRocks** [comment]
Just for some background, The colors and indices in the current default config are made from the options available in Maya <= 2015. I gave them those names because they were my best guess at what they should be called.

Do you think users will still want to indiicate the colors by the Maya indices or should be just scrap that option all together (I'm OK with scrapping it because it wasn't a smart way to do colors in the first place).

**Comment by todderasesareddot** [comment]
Yeah.  Makes total sense since Maya's color index was so limiting.  
But now, we should leave Maya indices in the dust where they belong.  No need for them anymore.  I like using names, though, because it's easy to tell what's going on when writing a component if people want to know what a particular named color is, they can look it up on the web.  Obviously, we should support RGB as well.

**Comment by EricTRocks** [comment]
Yes agreed.

**Comment by todderasesareddot** [comment]
We can add code in the maya path that checks for version and does something smart-ish with colors and indices.

**Comment by EricTRocks** [comment]
It would be cool if there would be a way to find the closest color to one of the Maya indexed colors and map to the index of that closest one for Maya 2014 <

**Comment by todderasesareddot** [comment]
I think there are just 32 colors, so we just need to map to that Maya index color space.  Should be fun.  :)

**Comment by BigRoy** [comment]
Fun discussion guys. 

But yes, revamp the color mapping to support RGB and HTML color code names. +1

I like the idea of having a "mapping to closest Maya index" method. Though I'd think it's more for the fun of it than actual useful (outside of its obvious use for backwards compatibility with 2014-). The backwards compatibility will be less important over time I suppose. By the way, how far back is Fabric Engine actually supported, 2014-ish?

**Comment by EricTRocks** [comment]
Fabric still supports 2014 so we'll try to keep pace with official Fabric support. Though I don't have access to 2014. :\

**Comment by todderasesareddot** [comment]
I've got it at home, I think.
