### ISSUE TITLE
'Paste Mirrored' feature semi-broken in mjEyelid Component

### ISSUE THREAD

**Issue by mjcg91** [fabric-engine/Kraken#341]
Doing a "paste mirrored" with mjEyelid does not make the mirrored component to appear in the graph anymore. The component's data are mirrored and the Guide and Rig can build without problem. Only the mirrored component is invisible in the graph.

Is this related to the changes with the data arguments ?

**Comment by EricTRocks** [comment]
I don't think so I think this is related to some core changes I made recently. Will investigate in the next few days.
