### ISSUE TITLE
Implement proper logger in Kraken

### ISSUE THREAD

**Issue by EricTRocks** [fabric-engine/Kraken#381]
A proper use of the logging module in python would be very beneficial. Having print statements everywhere and having to add / remove debug print statements is very annoying. 

If a proper use of the logging modules was implemented, we could leave in calls to `logger.debug()` and set the normal level of the kraken logger to `INFO`. Then when debugging we could set the level to `DEBUG`

Additionally, loggers allow you to setup custom handlers. These handlers can send the output to various places such as files, emails, etc. The main interest here is to send messages to a Widget Handler that would update widgets when new messages were sent to a logger. Also this may help sending messages to the splash screen.

**Comment by todderasesareddot** [comment]
Yes, please!
