### ISSUE TITLE
Softimage builder.py indentation error

### ISSUE THREAD

**Issue by yamahigashi** [fabric-engine/Kraken#410]
After f6e7339
https://github.com/fabric-engine/Kraken/blob/develop/Python/kraken/plugins/si_plugin/builder.py#L1366-1369
```python
                        if arrayNode is not None:

                        else:
                            addCanvasPorts(canvasOp,
                                           portName + str(j),
                                           arrayNode + ".value" + str(j),

```

These line cause indentation error in softimage when builder called.

> \# allocating an instance of QApplication
> \# INFO : [KL]: [FABRIC:MT] Loaded extension Animation in 33.932ms (cached)
> \# INFO : [FABRIC:MT] Loaded extension Animation in 33.932ms (cached)
> \# INFO : [KL]: [FABRIC:MT] Loaded extension Kraken in 74.692ms (cached)
> \# INFO : [FABRIC:MT] Loaded extension Kraken in 74.692ms (cached)
> \# INFO : [KL]: [FABRIC:MT] Loaded extension KrakenForCanvas in 47.362ms (cached)
> \# INFO : [FABRIC:MT] Loaded extension KrakenForCanvas in 47.362ms (cached)
> \# INFO : expected an indented block (builder.py, line 1368)

It seems "else:" line does not need.

**Comment by EricTRocks** [comment]
@yamahigashi If you get the latest develop zip from the site you'll get these fixes.
