### ISSUE TITLE
Support blend shapes driven attrs in KL build

### ISSUE THREAD

**Issue by todderasesareddot** [fabric-engine/Kraken#415]
Helge added a getShapeNames() and getShapeWeights() to the kl builder, but there was still nothing in Kraken to drive those shapes.  We need a way in Kraken to designate these shape names and to drive these shape attributes.

**Comment by EricTRocks** [comment]
Fixed in 016cc79.

Implemented new meta data on objects that the KL builder will use to look up blend shape attrs and associations.
