### ISSUE TITLE
Unify parenting operations

### ISSUE THREAD

**Issue by todderasesareddot** [fabric-engine/Kraken#444]
Need to make sure all parenting/unparenting operations are consistent no matter how you do it.

**Comment by EricTRocks** [comment]
Are there instances where this isn't the case? If so which ones?

**Comment by todderasesareddot** [comment]
All objects subclassed from SceneItem had a setParent() method.  That means if you call setParent() on an object3D it would set the _parent attribute, but it would never add that object as a child to the parent or do the name clash checking.  Now, you can call   parent.addChild(child) or child.setParent(parent) and get the same exact correct result no matter the object types.

**Comment by EricTRocks** [comment]
This work was merged. Thanks!
