### ISSUE TITLE
Update Kraken UI to work with Maya 2017

### ISSUE THREAD

**Issue by todderasesareddot** [fabric-engine/Kraken#464]
I hate how maya imports everything into the main namespace, but...

Maya 2017 uses PySide2. To use PySide in your scripts, import modules from PySide as follows. This allows your script to be compatible with both Maya 2017 as well as versions earlier than Maya 2017.

```
try:
    from PySide2.QtCore import * 
    from PySide2.QtGui import * 
    from PySide2.QtWidgets import *
    from PySide2 import __version__
    from shiboken2 import wrapInstance 
except ImportError:
    from PySide.QtCore import * 
    from PySide.QtGui import * 
    from PySide import __version__
    from shiboken import wrapInstance 
```

**Comment by todderasesareddot** [comment]
Some classes have moved around.  Note the new QtWidgets package

**Comment by BigRoy** [comment]
Maybe have a look at using [Qt.py](https://github.com/mottosso/Qt.py)? It'll help building a cross-compatible app between multiple Qt versions, e.g. PySide and PySide2.

**Comment by EricTRocks** [comment]
Initial work on this is currently available. We've integrated Qt.py within Kraken to get the compatability with PySide2. However there are now offests with port labels and port circles that will be addressed shortly.

**Comment by EricTRocks** [comment]
Fixed
