### ISSUE TITLE
Enable Parallel Eval of Canvas Operators in Maya by default

### ISSUE THREAD

**Issue by EricTRocks** [fabric-engine/Kraken#466]
Currently Canvas Operators built through Kraken do not run in Parallel because the `FabricCanvasSetExecuteShared()` command isn't run on them.

This is super important to ensure operators are running as fast as possible

@todderasesareddot @bhaux this is an item we found that may be interesting to you.

**Comment by todderasesareddot** [comment]
Absolutely!  We've noticed canvas nodes not efficiently running in parallel mode.  I had no idea there was this setting.  Can't wait to try this!

**Comment by bhaux** [comment]
they DONT?! Eric it's not April 1st.
Wow! 😂
