### ISSUE TITLE
Error connecting attributes that are locked

### ISSUE THREAD

**Issue by todderasesareddot** [fabric-engine/Kraken#473]
If you lock object attributes in a component and also try to connect to them you get an error because kraken locks the attribute when the node/attr is created in the DCC and fails later when it does connections.

I'll submit a PR for this in a few minutes...

**Comment by EricTRocks** [comment]
This will be done in a separate pass after everything else has been done to the object hierarchy. The work will be done in the core/builder.py as this will not require any changes to the kraken plugin builder.py files.
