### ISSUE TITLE
kraken bob rig is not built correctly when maya units are set to meters

### ISSUE THREAD

**Issue by helgemathee** [fabric-engine/Kraken#486]

**Comment by EricTRocks** [comment]
@reality3d @helgemathee This is a bit problematic to fix as this would mean we need an input into every solver to compensate for the unit difference and also update all solvers to utilize this unit difference as well. Any suggestions?

I would prefer to just log a message that Kraken must use centimeters when building and have the user switch to centimeters to build. We could also do this automatically as well before building, then restore the original value.

**Comment by reality3d** [comment]
@helgemathee @EricTRocks I think it is fine at this point to log the warning that we only support building the rig in centimeters. In the future, we should take the scene units into consideration. In any case, other than the bones/locator positions how is that the solvers are dependent on the units?

**Comment by EricTRocks** [comment]
@helgemathee @reality3d Length values that users set need to also be scaled appropriately. This can be done by exposing a global that users can use in their components if they choose to use millimeters.

However there also seems to be an with the `FabricConstraint` node. It's not correctly reflecting the actual values of the input matrix. it's multiplying them by 0.1
