### ISSUE TITLE
Graph positions don't get saved/loaded properly

### ISSUE THREAD

**Issue by bhaux** [fabric-engine/Kraken#503]
lately, when working in a graph the graph positions don't get set/loaded properly anymore

[Graph_positions_break.zip](https://github.com/fabric-engine/Kraken/files/869453/Graph_positions_break.zip)

**Comment by bhaux** [comment]
may be related to https://github.com/fabric-engine/Kraken/issues/508

**Comment by bhaux** [comment]
I could verify the 503 branch works for components but not backdrops...
And a little polish node (unrelated to this issue) - backdrops should probably be created under the mouse cursor position,

**Comment by bhaux** [comment]
Pulled 503 - Moving backdrops doesn't yet work 

# Traceback (most recent call last):
#   File "X:\dev\fabric\kraken\Python\kraken\ui\GraphView\kbackdrop.py", line 370, in mouseMoveEvent
#     self.__graph.moveSelectedNodes(delta)
#   File "X:\dev\fabric\kraken\Python\kraken\ui\GraphView\pyflowgraph\graph_view.py", line 327, in moveSelectedNodes
#     node.translate(delta.x(), delta.y())
#   File "X:\dev\fabric\kraken\Python\kraken\ui\GraphView\kbackdrop.py", line 267, in translate
#     super(KBackdrop, self).translate(x, y)
# AttributeError: 'super' object has no attribute 'translate'

**Comment by EricTRocks** [comment]
Fixed
