### ISSUE TITLE
Operator Arguments should support default values that are unconnected to values in the DCC

### ISSUE THREAD

**Issue by phtaylor** [fabric-engine/Kraken#78]
We might want to expose a bunch of parameters, that a TD will not connect. 
It should be easy to support default values (e.g. Color) that then are optional.

A new method on operators is probably needed for this:
.setArgValue()

- [ ] Implemented in Maya
- [ ] Implemented in Softimage

**Comment by EricTRocks** [comment]
@phtaylor Need some insight into what this request relates to. Splice / Canvas op arguments?

**Comment by todderasesareddot** [comment]
[1/27/16, 2:12 PM] Todd Taylor (todderasesareddot@gmail.com):  Right now if you add an new optional param to an operator and people are using that op in their components, they currently will need to update their components for it not to throw an error.

**Comment by EricTRocks** [comment]
@todderasesareddot is this still the case or did the changes to the operators also solve this? We can now set static values on arguments (in Maya, Softimage soon) so I think this is solved.

**Comment by EricTRocks** [comment]
This has been implemented for Maya starting in this commit cc5a11a. This still needs to be done and validated for Softimage.

**Comment by todderasesareddot** [comment]
This is different than being able to set static values.  This is setting no values at all.  For example, if you add an input to an operator, but do not update component code to make connections or set a value, the component code will fail.
